### ISSUE TITLE
Package installation issue

### ISSUE THREAD

**Issue by jakespice** [wiscostret/fplscrapR#8]
I have tried to get started with the fplscrapR package as per the readme using RStudio v1.2.5001:

>if (!require(remotes)) {
  install.packages("remotes") 
}

> remotes::install_github("wiscostret/fplscrapR")

> library(fplscrapR)

However the following error is occuring:

> ERROR: dependency 'vctrs' is not available for package 'pillar'
> * removing 'C:/Users/HP/Documents/R/win-library/3.3/pillar'
Error: Failed to install 'fplscrapR' from GitHub:
  (converted from warning) running command '"C:/PROGRA\~1/R/R-33\~1.2/bin/x64/R" CMD INSTALL -l "C:\Users\HP\Documents\R\win-library\3.3" C:\Users\HP\AppData\Local\Temp\RtmpGUcyj8/downloaded_packages/pillar_1.4.2.tar.gz' had status 1
> library(fplscrapR)
Error in library(fplscrapR) : there is no package called ‘fplscrapR’

Much appreciated!

**Comment by wiscostret** [comment]
Thanks for posting. This issue seems unrelated to the fplscrapR install, which does not rely on either 'vctrs' or 'pillar'

Rather, it seems to relate to the install of 'vctrs' and/or 'pillars'. 

Most likely you are updating these packages when installing fplscrapR. When using the install_github command, it will prompt you to update other packages that are available on CRAN ("These packages have more recent versions available. Which would you like to update?"). You can sidestep this by replying with an empty line (or '3' for 'None').

Alternatively, you can try installing the packages in question manually before installing fplscrapR. You can e.g. do so using: install.packages(c("vctrs", "pillar"))

Hope this solves the issue.

**Comment by jakespice** [comment]
I tried the above but get the following:
>  There are binary versions available but the source versions are later:
       binary source needs_compilation
rlang   0.2.0  0.4.0              TRUE
curl      3.2    4.2              TRUE
pillar  1.2.1  1.4.2             FALSE

> Binaries will be installed
Packages which are only available in source form, and may need compilation
  of C/C++/Fortran: ‘vctrs’ ‘ellipsis’
  These will not be installed

It has been a long while since I used R so I also used this to try update all packages:
> update.packages(checkBuilt=TRUE, ask=FALSE)

Still getting the same error message as in the first post.

**Comment by wiscostret** [comment]
Again this has to do with the installation of other packages (rlang/curl/pillar/vctrs/ellipsis) and not fplscrapR. Installing fplscrapR without prompting the install of other packages (by entering empty, '3' or 'n' (for no) when asked to update those other packages) should resolve your issue.

I can't unfortunately troubleshoot the installation of unrelated packages - but this seems a regular issue that is discussed at the RStudio forums (see e.g. https://community.rstudio.com/t/unable-to-install-rlang/17966/3) or StackOverflow (https://stackoverflow.com/questions/31249980/error-in-r-package-which-is-only-available-in-source-form-and-may-need-compil).

**Comment by jakespice** [comment]
Even the installation without prompting the installation of other packages isn't giving me any luck but I will try dig a little deeper on stack exchange regarding the other packages if its not to do with fplscrapR.

Thanks for getting back to me
